name: prediksi_suhu_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - mlflow
  - matplotlib
  - seaborn
  - pip:
      - boto3
